### ISSUE TITLE
speech_recognition ASR recipe template OOM

### ISSUE THREAD

**Issue by ChenYang-ChenYang** [speechbrain/speechbrain#1009]
I tried to train the speech_recognition ASR recipe template with mini_librispeech data but got GPU OOM while setting batch size=4. It worked well if the batch size<=3. My GPU is RTX 2080, with 11G memory.

I read the https://github.com/speechbrain/speechbrain/issues/918 and got to know either reducing batch size or beam search size can resolve OOM. I changed both the valid_beam_size and test_beam_size to 1 but the max working batch size is still 3.

My question are: 
1. Is this by design or is there a way to optimize the code to support larger batch size with the same GPU?   
2. Is the OOM mainly caused by some wav/flac data that are long in the batch and use much memory?

**Comment by TParcollet** [comment]
There is no way to "optimize" the code. SpeechBrain is already pretty close to Pytorch, so you would have to optimize pytorch. Things you can do are: make sure that you don't have sentences longer than 30s (and it's already pretty long imho). The last thing you can try is dynamic batching. If you don't use webdataset, have a look [here](https://github.com/speechbrain/speechbrain/pull/472/files). That is a PR with an example of Dynamic Batching for standard datasets. We don't have a tutorial about that because we need to test it and simplify it. But if you play with that, you will be able to create "buckets". This means that for long sentence you will explicitily reduce the batch_size, while you will increase it for short sentences. We also have one tutorial for Dynamic Batching with WebDataset :-)

**Comment by ChenYang-ChenYang** [comment]
> There is no way to "optimize" the code. SpeechBrain is already pretty close to Pytorch, so you would have to optimize pytorch. Things you can do are: make sure that you don't have sentences longer than 30s (and it's already pretty long imho). The last thing you can try is dynamic batching. If you don't use webdataset, have a look [here](https://github.com/speechbrain/speechbrain/pull/472/files). That is a PR with an example of Dynamic Batching for standard datasets. We don't have a tutorial about that because we need to test it and simplify it. But if you play with that, you will be able to create "buckets". This means that for long sentence you will explicitily reduce the batch_size, while you will increase it for short sentences. We also have one tutorial for Dynamic Batching with WebDataset :-)

Thanks for the reply. That makes sense and I will close it.
