### ISSUE TITLE
nan Loss in RNNLM training

### ISSUE THREAD

**Issue by 73minerva** [speechbrain/speechbrain#1020]
Hi,
I try to train a  RNNLM with a char level tokenizer and vocab size of 39. And Here is my modification on defult config yaml file: 
````
# Model parameters
emb_dim: 64 
rnn_size: 512 
layers: 2 
output_neurons: 39
````

Everything seems fine, until epoch 3 that I face with this error:
````
Exception occures in loss computation Loss is not finite and patience is exhausted. To debug, wrap `fit()` with autograd's `detect_anomaly()`, e.g.

with torch.autograd.detect_anomaly():
        brain.fit(...)
speechbrain.core - Loss is nan.
````
Also loading the last checkpoint doesn't work.

**Comment by TParcollet** [comment]
Hi, yeah that is quite a problem usually .. This can be caused by may things — very very long sentences / weird sentences (full of rare tokens) — very very short sentences ... One thing you could try is to train everything with AdamW instead of Adam and add a weight_decay of 0.01. However, I do not guarantee that this will work if it's a data problem. I think that you can halve the LR as well, from 0.001 to 0.0005.

**Comment by TParcollet** [comment]
Larger batch_size may help with that as well it will smooth the gradient. Do not hesitate to add some gradient_accumulation to be above 64 as an effective BS
