### ISSUE TITLE
Bug: VAD.get_boundaries(boundaries, output_value="seconds") returns too many indices for tensor of dimension 1

### ISSUE THREAD

**Issue by antonakv** [speechbrain/speechbrain#1045]
Hello,

`VAD.get_boundaries(boundaries, output_value="seconds")` fails with `too many indices for tensor of dimension 1`

Code:
```
from speechbrain.pretrained import VAD

VAD = VAD.from_hparams(source="speechbrain/vad-crdnn-libriparty", savedir="pretrained_models/vad-crdnn-libriparty")
print("Warming up")
boundaries = VAD.get_speech_segments("speechbrain/vad-crdnn-libriparty/example_vad.wav")
print("Interference")
boundaries = VAD.get_speech_segments("recorded/temp1.wav")
print("Getting boundaries")
result = VAD.get_boundaries(boundaries, output_value="seconds")
```

Attached compressed with zip wav file:

[temp1.wav.zip](https://github.com/speechbrain/speechbrain/files/7372551/temp1.wav.zip)

Modules used:
```
speechbrain        0.5.10
torch              1.9.1
torchaudio         0.9.1
huggingface-hub    0.0.19
```

Best regards,
Anton

**Comment by mravanelli** [comment]
Hi,
sorry for the late reply. You didn't call the function `get_boundaries` with the expected arguments (maybe you wanted to use the function `save_boundaries` here). Basically, the  `get_boundaries` function expects posterior probabilities (i.e, speech/nonspeech probs over the different time frames) and detects boundaries on top of it.  You probably wanted to print the boundaries with this:

`VAD.save_boundaries(boundaries)`

You can find detailed usage examples here:
https://huggingface.co/speechbrain/vad-crdnn-libriparty
Moreover, you can find a tutorial for that here: https://speechbrain.github.io/tutorial_classification.html

**Comment by antonakv** [comment]
Hello @mravanelli 

It's not about how I call the functions.

Please try to apply VAD to this specific wav file and you will hit the issue.

Best regards,

**Comment by mravanelli** [comment]
Hi @antonakv,
the correct way to use the VAD is the following:

```
from speechbrain.pretrained import VAD
VAD = VAD.from_hparams(source="speechbrain/vad-crdnn-libriparty", savedir="pretrained_models/vad-crdnn-libriparty")
boundaries = VAD.get_speech_segments("speechbrain/vad-crdnn-libriparty/example_vad.wav")
result = VAD.save_boundaries(boundaries)
```

This is the same example reported in the official [HF documentation](https://huggingface.co/speechbrain/vad-crdnn-libriparty) and runs smoothly on my side. Basically you have to use `VAD.save_boundaries(boundaries)`  instead of `VAD.get_boundaries`. The first is a function that we use to save the output of the VAD on a file (or to print it on the standard output like in this case). The `VAD.get_boundaries` has a different role, as you can see from the [code](https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/pretrained/interfaces.py#L1924)
