### ISSUE TITLE
Kaggle__RuntimeError: Backend "sox_io" is not one of available backends: ['soundfile']

### ISSUE THREAD

**Issue by loukasilias** [speechbrain/speechbrain#1086]
```
import torchaudio
from speechbrain.pretrained import EncoderClassifier
classifier = EncoderClassifier.from_hparams(source="speechbrain/spkrec-xvect-voxceleb", savedir="pretrained_models/spkrec-xvect-voxceleb")
signal, fs =torchaudio.load('../input/audio-files/audio_files/S001.wav')
embeddings = classifier.encode_batch(signal)
```

Running the above code in kaggle, I am getting the following error. How can I fix it? Thank you.
```
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_39/900806502.py in <module>
      1 import torchaudio
----> 2 from speechbrain.pretrained import EncoderClassifier
      3 classifier = EncoderClassifier.from_hparams(source="speechbrain/spkrec-xvect-voxceleb", savedir="pretrained_models/spkrec-xvect-voxceleb")
      4 signal, fs =torchaudio.load('../input/audio-files/audio_files/S001.wav')
      5 embeddings = classifier.encode_batch(signal)

/opt/conda/lib/python3.7/site-packages/speechbrain/__init__.py in <module>
      2 """
      3 import os
----> 4 from .core import Stage, Brain, create_experiment_directory, parse_arguments
      5 from . import alignment  # noqa
      6 from . import dataio  # noqa

/opt/conda/lib/python3.7/site-packages/speechbrain/core.py in <module>
     31 from torch.nn.parallel import DistributedDataParallel as DDP
     32 from hyperpyyaml import resolve_references
---> 33 from speechbrain.utils.distributed import run_on_main
     34 from speechbrain.dataio.dataloader import LoopedLoader
     35 from speechbrain.dataio.dataloader import SaveableDataLoader

/opt/conda/lib/python3.7/site-packages/speechbrain/utils/__init__.py in <module>
      9         __all__.append(filename[:-3])
     10 
---> 11 from . import *  # noqa

/opt/conda/lib/python3.7/site-packages/speechbrain/utils/metric_stats.py in <module>
     10 from speechbrain.utils.data_utils import undo_padding
     11 from speechbrain.utils.edit_distance import wer_summary, wer_details_for_batch
---> 12 from speechbrain.dataio.dataio import merge_char, split_word
     13 from speechbrain.dataio.wer import print_wer_summary, print_alignments
     14 

/opt/conda/lib/python3.7/site-packages/speechbrain/dataio/__init__.py in <module>
      9         __all__.append(filename[:-3])
     10 
---> 11 from . import *  # noqa

/opt/conda/lib/python3.7/site-packages/speechbrain/dataio/dataloader.py in <module>
     41 import functools
     42 from speechbrain.dataio.batch import PaddedBatch, BatchsizeGuesser
---> 43 from speechbrain.dataio.dataset import DynamicItemDataset
     44 from speechbrain.dataio.sampler import ReproducibleRandomSampler
     45 from speechbrain.utils.checkpoints import (

/opt/conda/lib/python3.7/site-packages/speechbrain/dataio/dataset.py in <module>
     11 from torch.utils.data import Dataset
     12 from speechbrain.utils.data_pipeline import DataPipeline
---> 13 from speechbrain.dataio.dataio import load_data_json, load_data_csv
     14 import logging
     15 

/opt/conda/lib/python3.7/site-packages/speechbrain/dataio/dataio.py in <module>
     24 
     25 torchaudio_backend = get_torchaudio_backend()
---> 26 torchaudio.set_audio_backend(torchaudio_backend)
     27 logger = logging.getLogger(__name__)
     28 

/opt/conda/lib/python3.7/site-packages/torchaudio/backend/utils.py in set_audio_backend(backend)
     42     if backend is not None and backend not in list_audio_backends():
     43         raise RuntimeError(
---> 44             f'Backend "{backend}" is not one of '
     45             f'available backends: {list_audio_backends()}.')
     46 

RuntimeError: Backend "sox_io" is not one of available backends: ['soundfile'].
```

**Comment by mravanelli** [comment]
which version of torchaudio are you using?  it looks like you are using a very old version.

**Comment by loukasilias** [comment]
kaggle has the version 0.9.1. How can I upgrade it?

**Comment by mravanelli** [comment]
it should work, but for some reason it looks like the sox-io front-end is
not available. You can anyway change it to soundfile here:
https://github.com/speechbrain/speechbrain/blob/68a8b5979dc5d6a885489d9a0428682d5a2ac012/speechbrain/utils/torch_audio_backend.py#L18

**Comment by loukasilias** [comment]
I am sorry but I didn't understand what I should change.
The error arises when I import the speechbrain. So what should I do before importing the library?

**Comment by ADD-eNavarro** [comment]
I've had exactly the same problem, and as @loukasilias 16 months before, this answer didn't help.
I've found that the issue here is that the library (soundfile) doesn't get installed with speechbrain, so I installed it manually. 
Then, same thing happened with "pytest". Installe manually and now I get:

Command:
SpeechBrain\speechbrain\recipes\AMI\Diarization>python experiment.py hparams/xvectors.yaml

Return:
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
torchvision is not available - cannot save figures
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
Traceback (most recent call last):
  File "C:\Users\eNavarro\Desktop\Diarización cmd\SpeechBrain\speechbrain\recipes\AMI\Diarization\experiment.py", line 513, in <module>
    params = load_hyperpyyaml(fin, overrides)
  File "C:\Users\eNavarro\Desktop\Diarización cmd\SpeechBrain\env_Speechbrain\lib\site-packages\hyperpyyaml\core.py", line 154, in load_hyperpyyaml
    yaml_stream = resolve_references(
  File "C:\Users\eNavarro\Desktop\Diarización cmd\SpeechBrain\env_Speechbrain\lib\site-packages\hyperpyyaml\core.py", line 308, in resolve_references
    _walk_tree_and_resolve("root", preview, preview, overrides, file_path)
  File "C:\Users\eNavarro\Desktop\Diarización cmd\SpeechBrain\env_Speechbrain\lib\site-packages\hyperpyyaml\core.py", line 359, in _walk_tree_and_resolve
    current_node[k] = _walk_tree_and_resolve(
  File "C:\Users\eNavarro\Desktop\Diarización cmd\SpeechBrain\env_Speechbrain\lib\site-packages\hyperpyyaml\core.py", line 369, in _walk_tree_and_resolve
    raise ValueError(f"'{key}' is a !PLACEHOLDER and must be replaced.")
ValueError: 'data_folder' is a !PLACEHOLDER and must be replaced.

And that's where I'm stuck.
