### ISSUE TITLE
ECAPA not trained with MFCC's?

### ISSUE THREAD

**Issue by dominickrei** [speechbrain/speechbrain#1178]
Hello,

I am training the ECAPA model from scratch using the provided [VoxCeleb recipe](https://github.com/speechbrain/speechbrain/blob/9df49e17c018c9617dfd3161a7db50a75086603e/recipes/VoxCeleb/SpeakerRec/hparams/train_ecapa_tdnn.yaml) and noticed that the features being computed to train the model are log-Mel spectrograms rather than the MFCC's described in the ECAPA paper. The model's performance is still great, but I am curious if there is a reason for this difference.

Thank you

**Comment by mravanelli** [comment]
Hi,
using MFCCs with a convolutional neural networks is usually not ideal. MFCCs are computed with a cosine transformation that decorrelates the coefficients. CNNs, instead, are designed to model local correlations that are in part neutralized by the cosine transformation.  Note that this is mainly an issue with conv2d and in general things work well anyway. As @Jenthe can confirm, however, their following papers on ECAPA-TDNN used FBANKs instead of MFCCs.

**Comment by dominickrei** [comment]
Ahh, very helpful to know! I also see now that they use mel-filterbanks as input in their recent paper on ECAPA-TDNN for speaker diarization. 

Thank you for the explanation
