### ISSUE TITLE
Metricgan+ pesq: No utterances detected'

### ISSUE THREAD

**Issue by wesleyck** [speechbrain/speechbrain#1217]
When i train the model，there is always an error with 
"  File "pesq/cypesq.pyx", line 171, in cypesq.cypesq
  File "pesq/cypesq.pyx", line 193, in cypesq.cypesq
cypesq.NoUtterancesError: b'No utterances detected'"

And i have install pesq with "pip install pesq",
here is my envs:
![image](https://user-images.githubusercontent.com/26861188/147734411-c92cd9ac-50fd-4885-8ccb-8f8df71cbb10.png)

Waiting for your reply!

**Comment by mravanelli** [comment]
Thank you for reporting it. @JasonSWFu, could you please double check if that happens to you as well with the latest version of the pesq library?

**Comment by ycemsubakan** [comment]
I have recently tried this recipe and I was able to train without error. However, @wesleyck , are you sure that you have generated the Voicebank dataset correctly?  

Another thing you can try would be to see if pesq function works in isolation. That is just try to run the pesq function separately from the recipe, and see if you get the same error.

**Comment by hjwang0086** [comment]
Same issue here when running on dataset other than Voicebank (such as DNS-Challenge dataset). It seems to be the issue from the original pesq package and only happens for some mini-batches. My temporary workaround is to use try/except NoUtterencesError while training and skip the batch if error occurs.
By the way, stoi may also sometimes cause RuntimeError if trained on other dataset, and it seems to be cause from removeSilentFrames. In pystoi package, it shows RuntimeWarning for handling the error.

**Comment by Cagemoney** [comment]
Hello,have you solved this problem? I also had this problem and it bothered me for a long time.

**Comment by LiamHorton** [comment]
Any update on this problem?

**Comment by bigsealing** [comment]
[temp2.zip](https://github.com/speechbrain/speechbrain/files/12034706/temp2.zip)


hi, these audio files will cause the problem , would you please resolve the problem ?

**Comment by taotaowang97479** [comment]
I have encountered the same issue. After debugging, I found that the problem is due to too many zero-filled samples in the processed audio segments, which makes it impossible to detect speech when calculating PESQ. The solution is to reduce the stride, for example, set the stride to 1 second, i.e., stride=16000 (when sr=16000) or even smaller.

**Comment by augusthuasheng** [comment]
How to reduce the stride? I check the parameter in PESQ, not found.

**Comment by taotaowang97479** [comment]
> How to reduce the stride? I check the parameter in PESQ, not found.

What I mean is in the data preprocessing stage rather than within PESQ. In the time-domain operation, we may use a stride, which is akin to the hop length in the frequency domain. If the stride is too large, it may result in filling too many zeros at the end of a speech segment, leading to errors as "No utterances detected". Therefore, the aim is to avoid having too many zeros in the speech segments, and other processing methods are also viable.
