### ISSUE TITLE
Unstable ASR inference results with pretrained model

### ISSUE THREAD

**Issue by gdimino** [speechbrain/speechbrain#1249]
I'm using the _speechbrain/asr-wav2vec2-commonvoice-it_ model from the HuggingFace repository to decode some Italian audio contents. With certain clips I'm getting some unstable results, that I try to resume shortly:

- Sometime only the first second of the sound clip are decoded, the rest is simply discarded even if it contains speech
- Sometime (maybe just choosing different clip boundaries) the problem mentioned in issues #924 and #911 is triggered even if the batch size is 1
- Sometime the output is garbage but splitting the clip differently works fine

The attached notebook and audio file show in practice the situation

[wav2vec2_issues.zip](https://github.com/speechbrain/speechbrain/files/7855630/wav2vec2_issues.zip)

**Comment by TParcollet** [comment]
Thanks for the notebook, it's pretty cool to try the bug as well. The issue is due to the attentional decoder that has been trained with audio with an average length of 4s (CommonVoice). This issue of truncation doesn't happen anymore with CTC only decoder (we have one for French for instance) ... We should retrain all our models with CTC only decoding :-/

**Comment by TParcollet** [comment]
@mravanelli maybe you should update the HF repo with the good IT model (CTC) ?

**Comment by mravanelli** [comment]
Yes, it makes sense to train it but we currently don't have it ready unfortunately.

**Comment by Adel-Moumen** [comment]
Hello, 

Please have a look at one of our new Italian model : https://huggingface.co/speechbrain/asr-whisper-medium-commonvoice-it it should answer your needs. 

Best. 
Adel
