### ISSUE TITLE
The error training of ECAPA-TDNN embeddings about datasets

### ISSUE THREAD

**Issue by LONG520520** [speechbrain/speechbrain#1292]
Hello:
When I train ecapa-tdnn with voxceleb2, I often have the following problems. I want to ask how to solve these problems? Hope to get a reply, thank you very much!
![image](https://user-images.githubusercontent.com/86965285/152754249-445d906d-c9c7-4ff2-919b-c4196cbfa4eb.png)

**Comment by LONG520520** [comment]
> Hello: When I train ecapa-tdnn with voxceleb2, I often have the following problems. I want to ask how to solve these problems? Hope to get a reply, thank you very much! !
![image](https://user-images.githubusercontent.com/86965285/154785414-41409939-512a-443c-a7a4-34290775f5ed.png)
![image](https://user-images.githubusercontent.com/86965285/154785450-dc84cb0a-d78d-4f91-9a58-c98fa2aab491.png)

**Comment by EddyGiusepe** [comment]
Hello @LONG520520, sorry for the inconvenience.

Were you able to solve this error? 

![image](https://user-images.githubusercontent.com/69597971/173202128-2ca6718e-8d70-4b55-ad87-d60acd6d7153.png)



Thank you very much!

**Comment by LONG520520** [comment]
NO,I don't have a perfect idea to  solve this error.

**Comment by mravanelli** [comment]
This error might happen when the number of output (i.e., the number of
speakers) is not set correctly. Could you please double check it? On my
side, I didn't have this error when training the embeddings.

**Comment by EddyGiusepe** [comment]
Good afternoon people!
I have some questions, I ask for your help to train a speakerID. My doubts are:

* I trained the speakerID following your [tutorial](https://colab.research.google.com/drive/1UwisnAjr8nQF3UnrkIJ4abBMAWzVwBMh?usp=sharing#scrollTo=b3tnXnrWc2My). But still my model does not perform well, because I still have little data (but I'm collecting it). Meanwhile, I was wondering how can I train my model with my data leveraging a pre-trained model (transfer-learning)?     .... I use voxceleb's pre-trained model, but even then I don't have any improvements yet.


* So I thought the following: [train_speaker_embeddings.py](https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxCeleb/SpeakerRec/train_speaker_embeddings.py) with voxceleb1+2 (I'm still downloading the data) and add particular noise (locomotive-train noise) and then use this trained model to train my [speakerID](https://github.com/speechbrain/speechbrain/tree/develop/templates/speaker_id) with my custom data from 48 speakers and with particular locomotive-train noise. Would this process be correct?


Thank you very much!

**Comment by underdogliu** [comment]
Thanks, @EddyGiusepe for your question, and allow me to try to answer them.

Before answering, I would like to clarify the difference between speaker ID (SID) and speaker verification (SV). Both of them sometimes can be misinterpreted as the speaker recognition problem, while being sub-problems of it.
* SID has one audio as input and decides which speaker the audio belongs to;
* SV has two audios (or two representations, as input) and decides if the two audios belong to the same speaker.
The tutorial you posted above focuses on the first problem, while a little bit of addressing the second one (Step 3). 

But despite which task you are dealing with, the speaker embedding extractor based on, for example, ECAPA-TDNN in the tutorial, is essential. If you want to train it from scratch, they normally need a huge amount of data with thousands of speakers to train. You can of course train another small classifier (e.g [PLDA](https://ieeexplore.ieee.org/document/6639151)) based on the output of the speaker embedding extractor, getting some reasonable performance. You can have a more detailed and maybe a bit mathematical description [here](https://wiki.aalto.fi/display/ITSP/Speaker+Recognition+and+Verification).

So to answer your two questions:
* Depends on whether the final downstream task is SID or SV. For SID, if you do not have a large amount of data, you better switch to something simpler rather than ECAPA-TDNN. In order to leverage the power of the pre-trained model, you can follow the approach described in [speaker_verification_plda.py](https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxCeleb/SpeakerRec/speaker_verification_plda.py), prepare the embeddings and train a PLDA classifier.
* If you are downloading VoxCeleb1+2, that will be great. Their training sets have ~7.2k speakers in total and you can confidently train an ECAPA-TDNN from scratch based on that. You can include the custom data in the training (but with repeating entries, as a dirty hack), or use your custom data to validate and tune the network performance. But the letter needs some thinking as we do not have that kinda solution in the repo. So, I would say yes you are correct in that.

**Comment by anautsch** [comment]
Closing here. Please feel free to re-open.
