### ISSUE TITLE
lm_corpus_path

### ISSUE THREAD

**Issue by fadlanhidayat** [speechbrain/speechbrain#1300]
Hi, I am trying to run recipes/librispeech/ using RNNLM, then in the RNNLM.yaml file there is a param called lm_corpus_path : null, I think there was an error because it didn't download automatically, so what kind of file that this param wanted to find? thank you

**Comment by anautsch** [comment]
Hi @fadlanhidayat sorry for responding late - going through the backlog.

We are taylking about this [RNNLM.yaml](https://github.com/speechbrain/speechbrain/blob/develop/recipes/LibriSpeech/LM/hparams/RNNLM.yaml) file, right?

And this line in particular:
https://github.com/speechbrain/speechbrain/blob/d78c00eca113c9f013f2eee4d05947adc1b32ccb/recipes/LibriSpeech/LM/hparams/RNNLM.yaml#L24

I ran on the Linux shell from the repo root:
```bash
$ grep -r lm_corpus_path recipes/LibriSpeech/
recipes/LibriSpeech/LM/train.py:        lm_corpus_path=hparams["lm_corpus_path"],
recipes/LibriSpeech/LM/hparams/transformer.yaml:lm_corpus_path: null
recipes/LibriSpeech/LM/hparams/RNNLM.yaml:lm_corpus_path: null
recipes/LibriSpeech/LM/dataset.py:    lm_corpus_path: Optional[str] = None
recipes/LibriSpeech/LM/dataset.py:        if self.lm_corpus_path is None:
recipes/LibriSpeech/LM/dataset.py:            self.lm_corpus_path = _DL_URL
recipes/LibriSpeech/LM/dataset.py:                    [self.config.lm_corpus_path] + files
```

The `dataset.py` script automatically sets:
https://github.com/speechbrain/speechbrain/blob/d78c00eca113c9f013f2eee4d05947adc1b32ccb/recipes/LibriSpeech/LM/dataset.py#L48

and it should be called here:
https://github.com/speechbrain/speechbrain/blob/d78c00eca113c9f013f2eee4d05947adc1b32ccb/recipes/LibriSpeech/LM/train.py#L115

The above YAML file is part of the recipe testing @mravanelli created since your posting - [compare item 68 here](https://github.com/speechbrain/speechbrain/blob/develop/tests/recipes.csv). At the time, we did not encounter errors - these tests happened after your posting.

Thus, I'm closing this issue - please feel free to re-open and comment further.
