### ISSUE TITLE
Fine tune asr-wav2vec2-commonvoice-fr

### ISSUE THREAD

**Issue by juliendespres** [speechbrain/speechbrain#1331]
Hi,

I have some questions about fine tuning. 
The tutorial on fine tuning ("Pre-trained Models and Fine-Tuning with") does not seem to apply to wav2vec models, especially the one trained on CommonVoice. The definition of modules for the model asr-wav2vec2-commonvoice-fr seems very different from the tutorial. 
I haven't found a script for fine-tuning on the git repository, wouldn't it be clearer to provide a fine-tuning script for each model or at least in the template directory, rather than having to copy pieces of code from the tutorial ? 
Finally, is fine-tuning a simple continuation of training but on other data, in which case it is sufficient to increase the number of epochs and continue training the pre-trained model or is the mechanism more subtle ?

Thanks in advance.

**Comment by TParcollet** [comment]
Hi, any recipe using a wav2vec 2.0 model or HuBERT or whatever from SpeechBrain is a "fine-tuning" appart from the actual pretaining recipe. Hence, https://github.com/speechbrain/speechbrain/tree/develop/recipes/CommonVoice/ASR/CTC this is fine-tuning with wav2vec 2.0 (train_with_wav2vec). Fine-tuning with wav2vec is different from standard SB fine-tuning because we rely on HuggingFace :/ It will change in the future, and we will change the tutorials accordingly.

**Comment by TParcollet** [comment]
Both can be achieved thanks to the Freeze parameter in the wav2vec class :-) Freezing is much faster and cheaper, but performance are not that great
