### ISSUE TITLE
TracerWarning in method get_padding_elem in nnet/CNN.py

### ISSUE THREAD

**Issue by groadabike** [speechbrain/speechbrain#1362]
Hi,

I am using the Layer Conv2D as defined in Speechbrain but get this message warning. 

`/export/raid1/users/gerardo/speechbrain/speechbrain/nnet/CNN.py:1120: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This me
ans that the trace might not generalize to other inputs!
  math.floor((L_in - dilation * (kernel_size - 1) - 1) / stride) + 1
/export/raid1/users/gerardo/speechbrain/speechbrain/nnet/CNN.py:1123: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This me
ans that the trace might not generalize to other inputs!
  math.floor((L_in - L_out) / 2),
/export/raid1/users/gerardo/speechbrain/speechbrain/nnet/CNN.py:1124: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This me
ans that the trace might not generalize to other inputs!
  math.floor((L_in - L_out) / 2)`

Cheers

**Comment by anautsch** [comment]
Hi @groadabike please provide a minimal snippet, so we can reproduce your observation.

**Comment by anautsch** [comment]
Confirmed running test.
```
pytest tests --cache-clear
pytest --doctest-modules speechbrain --cache-clear
```

**Comment by anautsch** [comment]
This relates to https://github.com/pytorch/pytorch/issues/32488 which is currently triaged. I looked through other jit related pytorch issues & PRs - filter:
> label:"oncall: jit"  TracerWarning 

Turns out, there is a lot of triaging regarding jit: https://github.com/pytorch/pytorch/projects/13#card-71745422
but I wasn't able to see a direct solution.

For the CNN part, the main issue is in the  speechbrain.nnet.CNN function `get_padding_elem(L_in: int, stride: int, kernel_size: int, dilation: int)` which takes `L_in` but `L_in` is a shape of a tensor. Jit keeps on tracing although it is not expected to do so - perhaps it is.

To test the issue locally, I added before the first warning at `speechbrain/nnet/CNN.py:1120` in line 1115:
```
L_in = int(L_in)
```
which resulted in the log:
> speechbrain/nnet/CNN.py:1115: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
    L_in = int(L_in)

If it's a dependency on pytorch issues, this one should be closed.

**Comment by groadabike** [comment]
Thank you @anautsch 
Should we worry about it? I mean, does it affect the padding? I am asking to be sure that I can safely use the CNN/Conv2D

**Comment by anautsch** [comment]
We discussed it internally a bit - please let me explain (can't give a direct yes/no answer). Certainly action needs to be taken here.
* so long as one is careful, it's fine (sparing comments.)
* if something changes between forwards, the risk is the first "L_out" value computed is returned

@Moumeneb1 pointed me to:
https://pytorch.org/docs/stable/onnx.html#avoiding-pitfalls
> PyTorch models can be written using NumPy or Python types and functions, but during [tracing](https://pytorch.org/docs/stable/onnx.html#tracing-vs-scripting), any variables of NumPy or Python types (rather than torch.Tensor) are converted to constants, which will produce the wrong result if those values should change depending on the inputs.

Currently open PRs on jit are #933 and #1142 - and it would certainly be good to have this issue addressed as well.
