### ISSUE TITLE
DEBUG    speechbrain.utils.superpowers:superpowers.py:93 -n hello

### ISSUE THREAD

**Issue by flckv** [speechbrain/speechbrain#1373]
<img width="591" alt="image" src="https://user-images.githubusercontent.com/103381497/162984002-c9e0f00a-cea0-47bf-ad43-5648ce562f08.png">
DEBUG    speechbrain.utils.superpowers:superpowers.py:93 -n hello

**Comment by anautsch** [comment]
Hi @felicia4 I cannot reproduce the error on my machine. Which operating system are you using?

I ran `pytest tests/unittests/test_superpowers.py` on an Ubuntu/Linux derivative without problems.
Then, I was curious for the `pytest.mark.skipif` decorator: `python -c 'import  sys;print(sys.platform)'` resulted in `linux`. It could be an issue with the `run_shell` function (which targets bash shells only).

**Comment by Adel-Moumen** [comment]
Hello @flckv,

I'm closing this issue as it has been inactive for a significant amount of time. If this is still an ongoing concern, I would encourage you to open a new issue with the updated issue template so that we have all the necessary information to investigate further.

Let me know if you have any questions or concerns.
