### ISSUE TITLE
[minimal issue- missing packages] Pesq and tensorboard missing from requirements.txt

### ISSUE THREAD

**Issue by sangeet2020** [speechbrain/speechbrain#1454]
I guess the requirement.txt file is missing the below packages:
- pesq
- tensorboard

Could we add them to avoid errors?

Thanks

**Comment by anautsch** [comment]
Hi @sangeet2020 both packages are handled by recipes via `extra_requirements.txt` or `extra_dependencies.txt` files to be installed with pip depending on which recipe is targeted. The reason is that not all recipes need these two packages for their minimal set-up. Unarguably, you are right in pointing out we should avoid errors. After glancing through recipes using pesq, not all of them have the package listed in such txt files for pip - some mention it in their readme files. This needs cleaning up and perhaps regular sanity checks.

@mravanelli @pplantinga how about extending recipe checks for their module imports & requirements?

**Comment by sangeet2020** [comment]
Seems reasonable. Thanks for clearing that up.
