### ISSUE TITLE
Torch 1.12 not compatible?

### ISSUE THREAD

**Issue by mjrog3** [speechbrain/speechbrain#1493]
working to install speechbrain 0.5.12, and getting the error that "speechbrain 0.5.12 requires torch<=1.11,>=1.7, but you have torch 1.12.0 which is incompatible." read elsewhere that it should work with >=1.7.

**Comment by TParcollet** [comment]
Hi,

Torch 1.12 just appeared, we can't guarantee that everything will work but from the patch note, we don't see any reason why it would break SB. Please try and let us know :-D

**Comment by kaylC4** [comment]
Meanwhile I found the following workaround on Colab:

**BEFORE installing speechbrain:**
`!pip uninstall torch`
`!pip uninstall torchvision`
`!pip uninstall torchtext`
`!pip uninstall torchaudio`

This should avoid all incopatibility issues.
Then I do not get the exact order to reinstall because while installing **torch**, it requires **torchvision**, and viceversa but at the it works for me:
`!pip install "torch==1.11.0"`
`!pip install "torchvision == 0.12.0"`
`!pip install "torchaudio == 0.11.0"`
`!pip install "torchtext == 0.12.0"`

And in the end install speechbrain
`!pip install -q speechbrain`

I try some use cases with **pyannote.audio (speaker diarization)** and it works

**Comment by TParcollet** [comment]
@pplantinga @lumaku is this linked to pypi?

**Comment by lumaku** [comment]
@TParcollet  Actually, I think it is the requirement from `setup.py`:
https://github.com/speechbrain/speechbrain/blob/bc3c7287e521a4b0927785f3fcb809d2ba90318a/setup.py#L40

**Comment by pplantinga** [comment]
It might be worth doing a small release (5.13) to address this.

**Comment by courentin** [comment]
Hello, any news on a small release ? :)

**Comment by sharvil** [comment]
@mravanelli, is there anything we can do to help get a release out with this version fix? We're having to go through all our deployment scripts and pin to PyTorch 1.11, which is fairly disruptive. I'd rather invest that time in getting this fix rolled out sooner, if possible.

**Comment by mravanelli** [comment]
Unfortunately, I cannot manage that at the moment but I hope someone from
the core team can move on and issue the minor version. Note that the dev
branch that you find on github is fine wuth torch 1.12.

**Comment by TParcollet** [comment]
@Gastron  or @pplantinga, could you please emit a small release for that? I can't today. I guess the release will include other things though ...

**Comment by pplantinga** [comment]
We have just released a small version: 0.5.13, hope this solves your issue!

**Comment by sharvil** [comment]
Thanks so much for getting the release out. I can confirm that it solves our deployment issue! :tada:
