### ISSUE TITLE
[Bug]: KsponSpeech/LM RepositoryNotFoundError

### ISSUE THREAD

**Issue by anautsch** [speechbrain/speechbrain#1784]
### Describe the bug

While [testing recipes](https://github.com/speechbrain/speechbrain/pull/1600#issuecomment-1335378632), it came up that a references HF repo was turned private.

Repository Not Found for url: https://huggingface.co/ddwkim/ksponspeech-conformer-medium/resolve/main/tokenizer.ckpt.

### Expected behaviour

https://huggingface.co/ddwkim/ksponspeech-conformer-medium is publicly available when being referenced in a recipe.

### Relevant log output

```shell
File "speechbrain/recipes/KsponSpeech/LM/train.py", line 187, in <module>
    run_on_main(hparams["pretrainer"].collect_files)
...
  File "huggingface_hub/utils/_errors.py", line 268, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Aj11wBz1puHa2Xtmbp8-r)

Repository Not Found for url: https://huggingface.co/ddwkim/ksponspeech-conformer-medium/resolve/main/tokenizer.ckpt.
Please make sure you specified the correct `repo_id` and `repo_type`.
If the repo is private, make sure you are authenticated.
Invalid username or password.
```

**Comment by anautsch** [comment]
@ddwkim @kimdwkimdw @starcell please help. We went through all recipes and found this dependency is required for one KsponSpeech recipe - it's about the tokenizer at:
https://huggingface.co/ddwkim/ksponspeech-conformer-medium/resolve/main/tokenizer.ckpt

The HF repo seems to have been put private. Is it possible to make it public again or make the tokenizer available?

@TParcollet wondering if the issue we had with conformer/transformer and other SB fixes over the last months would also have had a positive impact on ksponspeech-conformer-medium. I lost a bit track of what happened regarding conformer & scoring fixes or if all changes are even live by now (we might still be waiting on PR 751, dunno).

**Comment by ddwkim** [comment]
I apologize for this. I will look into the issue and get back to you as soon as possible.

**Comment by ddwkim** [comment]
The problem is due to hparams file for LM training indicating wrong location for tokenizer.ckpt.
The tokenizer.ckpt path should be https://huggingface.co/ddwkim/asr-conformer-transformerlm-ksponspeech instead.
Replacing the tokenizer path will fix the problem.
We are about to update the whole KsponSpeech model based on the new version of SpeechBrain, and will fix the bugs at the same time.

Meanwhile, I am still struggling with a problem of using `EncoderDecoderASR`. 
I trained the model with KsponSpeech dataset with LibriSpeech transformer ASR hparams file with conformer encoder, and everything works okay on script level.
However, when tried to run the model with pretrained interface, the model keeps generating erroneous results.
I am tracking down whether there are weight/architectural mismatches, but will PR the changes as soon as the issue is solved.
Please let us know if anyone faced a similar issue.

**Comment by anautsch** [comment]
What sort of errors are you getting with `EncoderDecoderASR` ?

Although you might have already, please update to the latest develop version. @Adel-Moumen is working on an improved scoring which could also impact this pretrained interface. I do remember others facing similar issues as with the KspoonSpeech recipes, so it's not on this set of recipes only. There were fixes but I lost track of how & which would relate to them.

Thank you for the upcoming PR!

**Comment by starcell** [comment]
The inference problem with EncoderDecoderASR can be corrected, but the source might not be modified yet.
I wrote about it on issue #1590
