### ISSUE TITLE
[Feature Request]: Option to turn off fetching pymodule_file for Pretrained.from_hparams

### ISSUE THREAD

**Issue by kamo-naoyuki** [speechbrain/speechbrain#1863]
### 🚀The feature

Issue:

When using Pretrained.from_hparams, I met an issue.

Even if pymodule_file doesn't exist, it tries to connect to huggingface for every invoking this function. This causes a HTTP connection error for isolated environment.

Proposal:

Implement an option to turn off the fetching the pymodule_file. Otherwise, for example, put a marker file to skip fetching when the fist fetching.

### Solution outline

-

**Comment by Adel-Moumen** [comment]
Hi @anautsch,

Coud you please take a look? Thanks :-)

**Comment by anautsch** [comment]
Hi @kamo-naoyuki yes - there's another way of how this can be handled (it's implemented, please allow me to clarify)

https://github.com/speechbrain/speechbrain/blob/e8cd583c07b12cb9c50b9b822df258268df75f8d/speechbrain/pretrained/interfaces.py#L303-L315

The argument
```python
pymodule_file="custom.py"
```
is as you stated, the Python interface for this module. Usually, it is 
* not in a repo (then a speechbrain.pretrained class serves as interface), e.g., https://huggingface.co/speechbrain/asr-crdnn-rnnlm-librispeech/tree/main
* or it has some name, e.g., https://huggingface.co/speechbrain/emotion-recognition-wav2vec2-IEMOCAP/blob/main/custom_interface.py where `custom_interface.py` != `custom.py`

The argument is handled right away:
https://github.com/speechbrain/speechbrain/blob/e8cd583c07b12cb9c50b9b822df258268df75f8d/speechbrain/pretrained/interfaces.py#L376-L396

It's here:
```python
  try:
    ...
  except ValueError:
     if pymodule_file == "custom.py": 
         # The optional custom Python module file did not exist 
         # and had the default name 
         pass 
```

---

About the HuggingFace talkativity, please use this environment flag, when calling python
```shell
TRANSFORMERS_OFFLINE=1 python ...
```
this will let the API still go into the HuggingFace Python modules, but it will disable the HuggingFace checking of meta information (latest, to wheter/not update - or just load from local cache).

---

Finally, with #1817 we will introduce a new namespace `FetchSource`, for if one likes to use e.g. local resources only and be very clear about that (one can declare not to use HuggingFace at all, e.g., after manually downloading everything elsewhere locally).

**Comment by kamo-naoyuki** [comment]
TRANSFORMERS_OFFLINE=1 python ...　works for me. Thank you

**Comment by kamo-naoyuki** [comment]
`TRANSFORMERS_OFFLINE=1 ` seems no effect. I still got a connection error.

I checked `https://github.com/speechbrain/speechbrain/blob/9033e80bd2312941a010a14f1b46747cad1f5746/speechbrain/pretrained/fetching.py#L120`, but it seems not to have some mechanism to refer  `TRANSFORMERS_OFFLINE`.

I'm not sure if I could tell you my problems correctly.

**Comment by kamo-naoyuki** [comment]
Let me clarify my situation:

- I downloaded the files obtained by `Pretrained.from_hparams` locally.
- I ran `Pretrained.from_hparams`  at offline environment, but I got a  HTTP error.
- `Pretrained.from_hparams` checks files exisitence, https://github.com/speechbrain/speechbrain/blob/9033e80bd2312941a010a14f1b46747cad1f5746/speechbrain/pretrained/fetching.py#L89, so if files alread exist, it can work at local environments. However, if the repository doesn't have`pymodule_file` in the repository, it tries to connect to huggingwave although I l already all downloaded all files

**Comment by anautsch** [comment]
Hi @kamo-naoyuki 

> `TRANSFORMERS_OFFLINE=1 ` seems no effect. I still got a connection error.

Please check:
https://huggingface.co/docs/transformers/v4.15.0/installation

It's a flag for HuggingFace libraries that might be used.

> I checked `https://github.com/speechbrain/speechbrain/blob/9033e80bd2312941a010a14f1b46747cad1f5746/speechbrain/pretrained/fetching.py#L120`, but it seems not to have some mechanism to refer `TRANSFORMERS_OFFLINE`.

Yes, this flag will be in a nested HF library.

> I'm not sure if I could tell you my problems correctly.

Sometimes communication doesn't work at once, so, then there are questions one can use.

Which HTTP error do you get? (with stacktrace)
Is the URL available?

Sometimes, a HF repo that was publicly available is turned "private" by the owner or sth. else changes, so that fetching meta information fails. Still, your point is that there shouldn't be any connection in the first place, right?

**Comment by anautsch** [comment]
> Let me clarify my situation:
> 
> * I downloaded the files obtained by `Pretrained.from_hparams` locally.

Then use that full local path instead. If it is the absolute path, then there will be no trigger to the huggingface_hub. Otherwise, the fetching mechanism tries to employ some magic to map a HF repo (if it can).

> * I ran `Pretrained.from_hparams`  at offline environment, but I got a  HTTP error.

Ok, got it - please forget my previous question about the stacktrace.

> * `Pretrained.from_hparams` checks files exisitence, https://github.com/speechbrain/speechbrain/blob/9033e80bd2312941a010a14f1b46747cad1f5746/speechbrain/pretrained/fetching.py#L89

Yes, please use absolute file names.

>   , so if files alread exist, it can work at local environments. 

Yes.

> However, if the repository doesn't have`pymodule_file` in the repository, it tries to connect to huggingface although I l already all downloaded all files

Or for any file in the repo. If you feed it a HF repo like "speechbrain/asr-..." then it will go into the HF branch at L120, and not into the L89 if-branch. After downloading from HuggingFace, please find out where it is put locally, and point to it with its absolute file path.

(As mentioned, soon the PR 1817 will be merged, and then one can also be very explicit about to fetch what from which source.)

**Comment by kamo-naoyuki** [comment]
Let me clarify.

Do you mean that, in the current state, before PR 1817 is merged, if I specified it as `speechbrain/asr-...`, there are no ways to run `Pretrained.from_hparams` in the offline environment?

> please find out where it is put locally, and point to it with its absolute file path.

Sorry, I don't have enough information about SpeechBrain's system.  Can the following  example work in the offline environment?

```ptyhon
Pretrained.from_hparams("/some/where/local/path")
```

**Comment by kamo-naoyuki** [comment]
Sorry, but I think, there are still some misunderstanding.

The model which I used is https://huggingface.co/speechbrain/spkrec-ecapa-voxceleb


` Pretrained.from_hparams("speechbrain/spkrec-ecapa-voxceleb")` can work in the offline environment except for custom.py.

You seemed to be writing that it tries to fetch meta information in spite of the existence of downloaded files, but actually such a fetching didn't work in my observation. My problem comes from only fetching `custom.py` in my environment. Indeed, with commenting the block of fetching `custom.py`, it works in the offline environment.

It's okay if `PR1817` solves all problems.

**Comment by anautsch** [comment]
PR 1817 will make it easier & more explicit. Before it is a working with the fetching module. Both ways will work now & then.

Yes, if you specify the "/some/where/local/path" instead of a HF repo short URL, it will work just as well.

Hm. Our tutorial also just uses short form URLs...
https://colab.research.google.com/drive/1LN7R3U3xneDgDRK2gC5MzGkLysCWxuC3?usp=sharing

Working on an example to clarify how you can get it working now.

**Comment by kamo-naoyuki** [comment]
Okay, I got it. Thank you for kind explanations.
