### ISSUE TITLE
[Bug]: wer_details_by_utterance fails if reference or hypothesis is None

### ISSUE THREAD

**Issue by rosyvs** [speechbrain/speechbrain#1917]
### Describe the bug

I am running (a lightly edited version of) the `train_with_whisper.py `recipe and encounter an error in validation.
When the WER metric is being computed for a batch, the refs and hypotheses are first run through the Whisper normalizer (which is fine) but this sometimes results in an empty list as the value in the `ref_dict` and/or `hyp_dict` for the affected utterance. 

Within` wer_details_by_utterance()` the keys/values in the `ref_dict `are iterated over, with the value assigned to the variable `ref_tokens` 

Presumably, based on the line below, the expected outcome of the normalisation in the case of an empty reference string after normalisation is that the `ref_tokens`  should be a list containing empty string (i.e. [""] instead of []).

When the reference is empty my code crashes at this line in wer_details_by_utterance(): 
```
        if ref_tokens[0] == "" and hyp_tokens[0] == "":
```
because ref_tokens is an empty list, i get` list index out of range`.

### Expected behaviour

I expected that if a reference is empty, the compute_objectives would proceed without error, instead returning (for example) None for the WER for that utterance if the reference is empty, and 100% for the WER if the hypothesis is empty (i.e. 100% deletions).

### Versions

Version 0.5.14 installed from pypi

**Comment by Adel-Moumen** [comment]
Hi @rosyvs,

Thanks for opening this issue! 

May I ask you if you could check if your fix works and if so, could you please open a pull request? It would help a lot... many thanks!

**Comment by rosyvs** [comment]
Sure, will do !

**Comment by Adel-Moumen** [comment]
Great! Please don't hesitate to reach out if you need any help

**Comment by Adel-Moumen** [comment]
> I expected that if a reference is empty, the compute_objectives would proceed without error, instead returning (for example) None for the WER for that utterance if the reference is empty, and 100% for the WER if the hypothesis is empty (i.e. 100% deletions).

I have been testing your proposal in #1919 however, it does not seems to do what you are describing. If you are setting the ref to be empty, you'll get an error saying that you can't divide by 0 (due to the WER computation). In the the case of empty hypothesis, the code in the develop branch is still working. However, in your new version, some things changed e.g. now some utterance will have `'hyp_empty': True` while they are not empty. 

I think the best solution is to directly modify the Whisper recipe by adding some checks after the normalization (e.g., if empty then set it to ''). 

Would you like to do it? 

Best.
Adel
