### ISSUE TITLE
[Bug]: Pretrain continue from checkpoint - how?

### ISSUE THREAD

**Issue by flckv** [speechbrain/speechbrain#1987]
### Last Checkpoint Specification - how?

Based on your tip I will need to pretrain for 7+ days. However, I will have to stop pretraining every 12 hours. 

https://github.com/speechbrain/speechbrain/blob/develop/recipes/LibriSpeech/self-supervised-learning/wav2vec2/hparams/wav2vec2_base.yaml

### Expected behaviour

What is the command or yaml part that I have to specify for continuing pretraining from last checkpoint? 

### To Reproduce

https://github.com/speechbrain/speechbrain/blob/develop/recipes/LibriSpeech/self-supervised-learning/wav2vec2/hparams/wav2vec2_base.yaml

**Comment by Adel-Moumen** [comment]
Please add this line to your yaml file: https://github.com/speechbrain/speechbrain/blob/develop/recipes/LibriSpeech/ASR/transformer/hparams/transformer.yaml#L43 

so that it will save your model every N minutes. Then when you will relaunch your training it will automatically fetch the latest checkpoint in your ckpt models.
