### ISSUE TITLE
Typing syntax not supported in 3.7/3.8

### ISSUE THREAD

**Issue by hughhop** [speechbrain/speechbrain#2536]
### Describe the bug

type hint syntax using square brackets e.g. ` -> tuple[list, list]` is used for many functions. this syntax was introduced in python 3.9 by [PEP 585](https://peps.python.org/pep-0585/)

the current documentation and requirements file imply that python versions >= 3.7 should be supported but if you try to use 3.7 or 3.8 it won't work. I think the documentation should be updated to that only python >=3.9 is supported.

### Expected behaviour

i expected to be able to `from speechbrain.inference.speaker import EncoderClassifier` with python 3.8.10 because it says in the documentation that >=3.7 is supported.

There is no issue in 3.9.13 and 3.12.3, but that is not clear from the documentation or requirements file.

### To Reproduce

from speechbrain.inference.speaker import EncoderClassifier

### Environment Details

windows 11. Bug found in python 3.8.10. No issues with 3.9.13 and 3.12.3.

### Relevant Log Output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python38\lib\site-packages\speechbrain\inference\__init__.py", line 5, in <module>
    from .ASR import *  # noqa
  File "C:\Python38\lib\site-packages\speechbrain\inference\ASR.py", line 519, in <module>
    class StreamingASR(Pretrained):
  File "C:\Python38\lib\site-packages\speechbrain\inference\ASR.py", line 790, in StreamingASR
    ) -> tuple[list, list]:
TypeError: 'type' object is not subscriptable
```

**Comment by Adel-Moumen** [comment]
Hi @hughhop, thanks for opening this issue! 

Could you please have a look @asumagic this is important :)

**Comment by asumagic** [comment]
The currently supported Python versions are 3.8-3.12, so this is a bug. I wasn't aware that the container hints were 3.9+ and I'm surprised the CI hasn't caught the issues since that runs on 3.8 and there seems to be a lot of uses of PEP 585 in the codebase... Will have to look into it.

Current documentation and the `setup.py` mention 3.8-3.12, it's also a bug if 3.7 is mentioned in some places. I can see some internal docs (e.g. coverage docs) mention older Python versions, though.

**Comment by asumagic** [comment]
Ah, nevermind, I got confused: `typing.Tuple[]` has existed for a while but `tuple[]` is 3.9+.

**Comment by hughhop** [comment]
I noticed the issue with 3.8 I only mentioned 3.7 because I noticed it at the top of the contributing.md.

If you just want to update everything to 3.9 in documentation I can try to do that and raise a pr but I wasn't sure if you actually want to support earlier versions.

I was only using 3.8 because of some other dependencies (long story)

**Comment by asumagic** [comment]
I will look into fixing the issue, relatively few code is actually affected.

**Comment by asumagic** [comment]
Actually, can you try [installing the latest git develop version of SpeechBrain](https://speechbrain.readthedocs.io/en/latest/installation.html#install-locally) (if that's not too complicated on Windows)? The issue might just be fixed already, I forgot that I had done similar fixes around this...

Inference with Windows might have other issues since SB relies on the use of symlinks in certain cases (which #2476 will fix, but it is not done yet).

**Comment by hughhop** [comment]
yes, that seems like that has fixed it. In python3.8 on windows installing speechbrain from commit 5beaece i can import the EncoderClassifier without issue since you are using the typing module.

This is a separate issue but to get it to install I had to set the environment variable PYTHONUTF8=1 otherwise `pip install --editable .` raised an error UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 457: character maps to <undefined>

also your comment about symlinks - to get pretrained models to download i need to run inside an administrator shell. once the model is downloaded then i can use a normal privilege level. seems like this won't be necessary in the future.

**Comment by asumagic** [comment]
Closing this since the original issue is fixed. I made a PR to potentially fix the text encoding issue.
