### ISSUE TITLE
Question: Can speechbrain accept mfcc streams?

### ISSUE THREAD

**Issue by StuartIanNaylor** [speechbrain/speechbrain#547]
Prob a silly question as likely what are the parameters of MFCC for speechbrain so I can send a MFCC stream.

I am working on a multiroom network mic solution that uses broadcast KW hit to select best stream and my KWS has 2 models one for KW & another for VAD/Diarisation where most of the load is the creation of the MFCC pipeline of a 20ms stream of S16_LE.

https://ai.googleblog.com/2021/02/lyra-new-very-low-bitrate-codec-for.html

The Lyra codec was a bit mweh to me as conversion from and back to audio is quite heavy in comparison to feeding a network ASR with an already computed MFCC stream.

Is that possible or could it be?

**Comment by mravanelli** [comment]
Yes, you can save store your mfccs in pkl files and read MFCCs directly. You can figure out how to do it, if you take a look into one of the existing recipes. The difference is that instead of reading audio files you have to read features. We understand your special need in your project but let me take this opportunity to remark anyway why in speechbrain we prefer on-the-fly feature computation:
1. Feature computation is super fast (especially on GPUs)
2. You can easily combine on-the-fly feature computation with on-the-fly data augmentation
3. The pipeline is cleaner and do not require annoying preliminary steps such as dumping feature on disk.
4. We can backpropagate the gradient through the features and make them learnable
5. Conceptually, we just see feature extraction as an early layer of a deep architectuere
