### ISSUE TITLE
Usage For Recognizer Model using GMM-HMM and such..

### ISSUE THREAD

**Issue by dmadhitama** [speechbrain/speechbrain#569]
Hello!!
Glad to see speechbrain finally on public!

Are there any usage examples for training the recognizer model using GMM-HMM and such as the some toolkit already applied (e.g: HMMLearn & Kaldi)?
If there are, can with speechbrain toolkit do data adaptation using pretrained recognizer model?

I have some dataset with same spoken word/phrase and I want to create recognizer model to recognize this single word/phrase.

Thank you.

**Comment by mravanelli** [comment]
The full HMM-DNN pipeline is not implemented yet (we gave priority to more
modern e2e systems). However, you can find the HMM alignment part here:
https://github.com/speechbrain/speechbrain/tree/develop/recipes/TIMIT/Alignment
In this example, we perform alignments based on forward or Viterbi
algorithms. A nice feature is that it doesn't use GMMs, but a small neural
network for the alignments. This makes the full pipeline more "modern"
because the HMM part is embedded in the cost function only. What is missing
is the FST decoding. For that, we plan to use the excellent FST toolkit
that kaldi2 is developing with PyTorch. This is something we will
probably add in the next version.
As for pretrained models, we have many of them. Take a look, for instance,
to our HuggingFace repo (https://huggingface.co/speechbrain/).
