### ISSUE TITLE
ECAPA-TDNN EER

### ISSUE THREAD

**Issue by Lallapallooza** [speechbrain/speechbrain#613]
Hello! I found that EER at vox1 is 0.69%, which is outstanding results.
But also I found in train_ecapa_tdnn.yaml that you're training and testing on the same data. In this file also I found that you're writing that testing on Vox1 incorrect if any files from Vox1 present in training.
So how can I interpret the 0.69% EER?

**Comment by mravanelli** [comment]
Hi, @Lallapallooza! thank you very much for your interest in the toolkit. What you pointed out is not actually happening. When we train the embeddings (with` train_speaker_embeddings.py`) the speaker used for verification are removed. This operation is done in the data preparation see:

https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxCeleb/voxceleb_prepare.py#L247 (see `L276` as well). This is why we ask to specify the verification list in the hyperparameter file of ecapa training (https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxCeleb/SpeakerRec/hparams/train_ecapa_tdnn.yaml#L24).  

We basically read this list and removing these speakers when training the embeddings.
To double-check it, you can take a look at the sentences that are listed in the `train.csv` file created during data preparation. You can see that there isn't any overlap with the speakers that you find listed in the specified verification list (e.g, https://www.robots.ox.ac.uk/~vgg/data/voxceleb/meta/veri_test2.txt).

Said that, I think we can comment better on this part to make it clearer. For instance, the comment you pointed out only refers to the subsets (VoxCeleb1-E and VoxCeleb1-H). Let me do some changes here. The EER is very good because we use a very powerful model like the ECAPA-TDNN one (with xvectors you have way worse performance). The performance that we achieve is in line with the latest numbers that you can find in the literature on Voxceleb.

**Comment by Lallapallooza** [comment]
Great, thanks for such a detailed answer.
