### ISSUE TITLE
Running two speechbrain models in 2 terminal tabs

### ISSUE THREAD

**Issue by maelfabien** [speechbrain/speechbrain#760]
Hi,

I'll remain very high level there since I did not dive deep enough into the code to actually offer a solution. I've made two apps that were running locally in a simple GUI. They both implied ASR + Speaker Id tasks, in speechbrain. However, one of my processes, once inference of the ASR system was called, kept failing and returned a very generic error:

```bash
zsh: killed     python main.py
````

I later figured out that two concurrent applications running speechbrain could not be supported on my local machine. I have no clue yet how to handle this, this is not a major problem for me, but maybe a specific error message could help there.

Thanks!

Mael

**Comment by TParcollet** [comment]
Hey, Are inferences run on GPU with DDP? @Gastron @pplantinga apart from a potential port / IP conflict from DDP, I don't see what could cause this ?!

**Comment by Gastron** [comment]
This is unexpected, but it looks like the error is not visible in the Python runtime - so we cannot influence the error message that gets reported. It looks like the whole Python process gets killed. This could be due to e.g. exceeding some memory limit or even some bug in the Python interpreter or a library that is being used.

**Comment by maelfabien** [comment]
Ok I see, I'm running on a local CPU, but it's indeed likely that it's a memory limit. I'll close this for the moment, and let you know if I find anything. Thanks a lot for your quick feedback
