### ISSUE TITLE
SincConv for audio with multiple channels

### ISSUE THREAD

**Issue by Hguimaraes** [speechbrain/speechbrain#774]
Hello everyone,

First of all, I would like to thank you guys for this amazing project. The SpeechBrain is saving me a lot of hours in my research.

Currently I'm doing a time-domain speech enhancement model and I would like to use SincConv as my initial layer.
My input is an 16kHz audio with 8-channels.

Even though the SincConv has a parameter "in_channels", for any values different of 1 is not possible to use it:

```python
inp_tensor = torch.rand([10, 16000, 8])
conv = SincConv(in_channels=8, out_channels=16, kernel_size=11)
out_tensor = conv(inp_tensor) 

""">> RuntimeError: Given groups=1, weight of size [16, 1, 11], expected input[10, 8, 16010] to have 1 channels, but got 8 channels instead"""
```

Is this the desired behaviour?

Best regards,

**Comment by TParcollet** [comment]
Glad to see that you find SpeechBrain useful :) 

@mravanelli the code of SincConv is from you I think. Is there a way to parallelize the SincConv over different channels? Maybe by *batching* the 8 channels instead ?

**Comment by Hguimaraes** [comment]
I did an initial "workaround" to get the module working.
I replicated the filter across the other dimensions, but I think this is conceptually strange.

```python
...
sinc_filters = self._get_sinc_filters()
sinc_filters = sinc_filters.expand(
    sinc_filters.shape[0],
    self.in_channels,
    sinc_filters.shape[2]
)
...
```

**Comment by mravanelli** [comment]
Yes, it is  definitely possible but it looks like the current version
supports a single channel (which is often the case when the input is a
single waveform). It could be great to extend it!

**Comment by lumaku** [comment]
Hey @mravanelli 
The `SincConv` that we implemented for Espnet (in https://arxiv.org/abs/2010.07597 ) supports multiple input channels. Would it make sense to merge these versions?
https://github.com/espnet/espnet/blob/master/espnet2/layers/sinc_conv.py
```python
import torch
from espnet2.layers.sinc_conv import SincConv
inp_tensor = torch.rand([10, 8, 16000]) # note: (B, C_in, D_in)
conv = SincConv(in_channels=8, out_channels=16, kernel_size=11)
out_tensor = conv(inp_tensor)
```

**Comment by mravanelli** [comment]
@lumaku, any PR for the multichannel support of sincnet is welcome!

**Comment by Gastron** [comment]
Hey @mravanelli, any updates on the multi-channel SincConv and multi-channel feature extraction in general? Should we close this issue?

**Comment by popcornell** [comment]
I think batching the 8 channels as @TParcollet proposed is the best way overall. Otherwise the front-end might risk overfitting the training set as it will be tied to the particular permutation of the input channels. But this depends on the actual back-end application which i don't know.

**Comment by lumaku** [comment]
Sorry for the delay on my part - I am too occupied with other tasks to contribute. If you find it useful or convenient, You are free to just copy the SincConv implementation that I wrote for the ESpnet toolkit; it would be just fair, as the it was heavily inspired by the original SincNet implementation! There would only be two things to look out for:
1. Speechbrain has a slightly different tensor dimension convention, it's `B, T, C, D` while the Espnet uses `B, C, T, D`. Reshape accordingly.
2. Speechbrains [SincConv](https://github.com/speechbrain/speechbrain/blob/4d7a971f98058ceb7192fcb29d4268b3aa12b1ce/speechbrain/nnet/CNN.py) implementation has additional checks that the other SincConv does not have. For example, it checks bandpass width, and some basic input shapes. Filter collapses never occurred in my training, if they happen in your training, then I highly recommend to initialize with Bark scale (broader at lower f) instead of Mel scale. The Espnet SincConv does not contain shape checks, as it is partly done by other modules, e.g. [`espnet2.asr.frontend.windowing`](https://github.com/espnet/espnet/blob/master/espnet2/asr/frontend/windowing.py). However, as module structures are very similar, this could be easily merged. (from my experience: Try to keep it efficient)

Regarding possible overfitting, this SincConv has shared weights over all input channels. I hope that helps!

**Comment by Hguimaraes** [comment]
Hi guys,

Sorry for the really late response. I've opened a PR with the suggestions from @lumaku that are presented in the espnet2 repository. I hope it fits well. The only condition, in both projects, is that by using groups in the convolution in order to batch, we need that the number of output channels is a multiple of in_channels. If it is possible I will try to work on a more general version in the next few days.

Best,

**Comment by Adel-Moumen** [comment]
Hello,

I close this issue because It seems that the problem has been fixed in [https://github.com/speechbrain/speechbrain/pull/1295](url) ! 🙂
