### ISSUE TITLE
Why does memory keep increasing， Is the cache not being freed？

### ISSUE THREAD

**Issue by wangzhang2991** [speechbrain/speechbrain#841]
I used Aishell's script to train the ASR model on my own data. During the model training process, the memory of the graphics card kept increasing and finally reported an out of memory error.

info:
  path: recipes/AISHELL-1/ASR/transformer
  train_data: 4000hr
  batch_size=1

Error:
  RuntimeError: CUDA out of memory.Tried to allocate 20.00 MiB...

**Comment by danpovey** [comment]
batch_size=1 is unusual.
How long is your longest utterance?  If you show the full error message it would help.

**Comment by TParcollet** [comment]
Hi @wangzhang2991, is it the wav2vec2 recipe or the "normal" one? Also, and as pointed by danpovey, the VRAM consumption is quite sequence-length dependent. a batch size of 1 with an "out of memory" error is most likely related to a sentence length issue. 

To answer your question, it depends. The VRAM consumption only increases because we keep the reserved memory locked. Hence, every time you see a longer sentence, your VRAM consumption will increase without going back to a smaller one. This is also expected if you have sorting=ascending.

**Comment by mravanelli** [comment]
Hi, 
the AI-SHELL wav2vec2 recipes are very memory demanding just because the model is big. I was able to train it with a single 48GB GPU with batch size=2. If you use other models such as the standard transformers or the CRDNN one are way less memory demanding. The memory occupation increases because you are probably using sorting=ascending, as mentioned by Titouan. This means that you start from the short sentences and then the longer ones (that need more memory to be processed). Note that you can exclude long sentences from training just by  setting the  "avoid_if_longer_than" flag in the YAML file (see an example here: https://github.com/speechbrain/speechbrain/blob/develop/recipes/CommonVoice/ASR/seq2seq/hparams/train_fr.yaml#L30)

**Comment by wangzhang2991** [comment]
> batch_size=1 is unusual.
> How long is your longest utterance? If you show the full error message it would help.

  Just started using the default configuration of the batch_size, found this error . Then I set the batch_size directly to 1 to rule out the problem caused by the value of the batch_size being too large. During this training, it was found that with the training, memory usage continued to grow until errors were reported.
   I checked utterance yesterday and it is too long. I tried to cull out some sentences. now, it is working fine. 
  Thank you!

**Comment by wangzhang2991** [comment]
> Hi,
> the AI-SHELL wav2vec2 recipes are very memory demanding just because the model is big. I was able to train it with a single 48GB GPU with batch size=2. If you use other models such as the standard transformers or the CRDNN one are way less memory demanding. The memory occupation increases because you are probably using sorting=ascending, as mentioned by Titouan. This means that you start from the short sentences and then the longer ones (that need more memory to be processed). Note that you can exclude long sentences from training just by setting the "avoid_if_longer_than" flag in the YAML file (see an example here: https://github.com/speechbrain/speechbrain/blob/develop/recipes/CommonVoice/ASR/seq2seq/hparams/train_fr.yaml#L30)



> Hi @wangzhang2991, is it the wav2vec2 recipe or the "normal" one? Also, and as pointed by danpovey, the VRAM consumption is quite sequence-length dependent. a batch size of 1 with an "out of memory" error is most likely related to a sentence length issue.
> 
> To answer your question, it depends. The VRAM consumption only increases because we keep the reserved memory locked. Hence, every time you see a longer sentence, your VRAM consumption will increase without going back to a smaller one. This is also expected if you have sorting=ascending.

Thank you for your help.  I was a little careless in cleaning the data. in my training data, there are some excessively long sentences over 70 utterances.

**Comment by wangzhang2991** [comment]
> Hi,
> the AI-SHELL wav2vec2 recipes are very memory demanding just because the model is big. I was able to train it with a single 48GB GPU with batch size=2. If you use other models such as the standard transformers or the CRDNN one are way less memory demanding. The memory occupation increases because you are probably using sorting=ascending, as mentioned by Titouan. This means that you start from the short sentences and then the longer ones (that need more memory to be processed). Note that you can exclude long sentences from training just by setting the "avoid_if_longer_than" flag in the YAML file (see an example here: https://github.com/speechbrain/speechbrain/blob/develop/recipes/CommonVoice/ASR/seq2seq/hparams/train_fr.yaml#L30)


 It's very helpful for me.  I've tried to set the "avoid_if_longer_than" flag in the YAML file.
 Thank you for your help!!
