### ISSUE TITLE
Torch version in requirements

### ISSUE THREAD

**Issue by Adlinga** [speechbrain/speechbrain#920]
Hi. It's not a bug, just a little thing.
In requirements.txt you mentioned torch>=1.7.1 but 1.7.1 don't have "rounding_mode" param in "div" function (you use it in decoders/seq2seq.py). It was added in 1.8.0.  There was a separate function "torch.floor_divide" In 1.7.1.

**Comment by csukuangfj** [comment]
I encountered the same error in seq2seq.py and spent some time figuring out that it actually requires at least torch 1.8.0.
I do consider it as a bug.

**Comment by mravanelli** [comment]
Fixed in the development branch, thank you!  Now the requirement is:
`torch>=1.8.0,<=1.8.1`
Note that pytorch 1.9 works as well. The only annoying thing is that there are some warnings raised internally by pytorch that they will be fixed in the next version (I already raised an issue in the pytorch repo for the warnings).
