### ISSUE TITLE
How to enable EarlyStopping in speech separation recipe

### ISSUE THREAD

**Issue by srdfjy** [speechbrain/speechbrain#962]
How to enable EarlyStopping in speech separation recipe？Thanks!

**Comment by TParcollet** [comment]
In practice, we really on elaborated learning rate schedulers instead of early stopping: https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/nnet/schedulers.py

But you can deploy early stopping with a specific epoch counter, like this one: 
https://github.com/speechbrain/speechbrain/blob/4d7a971f98058ceb7192fcb29d4268b3aa12b1ce/speechbrain/utils/epoch_loop.py#L71

**Comment by mravanelli** [comment]
As far as I remember we already have some recipes using early stopping. You
can take a look at this one for instance:
https://github.com/speechbrain/speechbrain/blob/develop/recipes/ERPCore/P3_decoding/train.py

**Comment by srdfjy** [comment]
> In practice, we really on elaborated learning rate schedulers instead of early stopping: https://github.com/speechbrain/speechbrain/blob/develop/speechbrain/nnet/schedulers.py
> 
> But you can deploy early stopping with a specific epoch counter, like this one:
> https://github.com/speechbrain/speechbrain/blob/4d7a971f98058ceb7192fcb29d4268b3aa12b1ce/speechbrain/utils/epoch_loop.py#L71

**Comment by srdfjy** [comment]
@TParcollet @mravanelli thanks!
