### ISSUE TITLE
Wrong log probabilities reported in seq2seq.py

### ISSUE THREAD

**Issue by PabloPeso** [speechbrain/speechbrain#978]
Hi,

I was trying to use the log probabilities from the decoder but I was always getting positive numbers. When I looked into the code I found that `topk_log_probs` reports the length of the decoded utterance instead of the log probability as shown below
https://github.com/speechbrain/speechbrain/blob/540071f1c146742166e7be42d3209d92ce4e6baf/speechbrain/decoders/seq2seq.py#L550

I have fixed it by replacing `top_lengths` by `top_log_probs`, this is `topk_log_probs = [top_log_probs[index.item()] for index in indices]`.

I hope this helps.

**Comment by mravanelli** [comment]
Thank you for noticing it. @30stomercury, could you please take a look?

**Comment by 30stomercury** [comment]
Hi @PabloPeso, thanks for spotting this.

I spotted this before and issue was fixed in #751 here:
https://github.com/speechbrain/speechbrain/blob/5d3b3fcc4353a78e38e647f99f9b034b804063bf/speechbrain/decoders/seq2seq.py#L530-L537 

But I think we can fix it for the `develop` now. Do you want to have a PR for this? I can then merge it.

**Comment by PabloPeso** [comment]
Hi @30stomercury,

Thanks for your reply. I think it is easier for now to wait for the 0.6.0 release which I understand it includes that fix, unless you'd rather do it now (I don't mind). I posted the comment to help debugging the code :-)

Cheers.

**Comment by 30stomercury** [comment]
Okay, let's wait for the 0.6.0 release :)
